### ISSUE TITLE
The NTVDM CPU has encountered an illegal instruction

### ISSUE THREAD

**Issue by ZeroTheSavior** [electronjs/grunt-electron-installer#108]
Installer immediately crashes. I was told to post here because it was an installer issue with GPMDP and not related to GPMDP itself

Windows 8.1, x86.

Screenshot
http://i.imgur.com/DwB5IXK.png

**Comment by paulcbetts** [comment]
wat

**Comment by paulcbetts** [comment]
Are you 100% sure that the file you downloaded isn't corrupted?

**Comment by ZeroTheSavior** [comment]
I downloaded it twice, so no?

**Comment by paulcbetts** [comment]
Hm, and you've never seen file corruption with other apps before? Something very wrong is happening if we're getting into NTVDM

**Comment by ZeroTheSavior** [comment]
read updated reply.
